# 1.2 Numpy包

In [1]:
import numpy as np

## 1.2.1 基本介绍  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Numpy与Python列表性能比较：  
问题：将包含一百个整数的数组乘二

In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000)) 
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = my_list * 2    

CPU times: user 16.6 ms, sys: 10.7 ms, total: 27.2 ms
Wall time: 30.8 ms
CPU times: user 107 ms, sys: 15.9 ms, total: 123 ms
Wall time: 124 ms


In [4]:
data = np.random.randn(2,3)

In [5]:
data

array([[-1.16604111,  0.25365658,  1.10927193],
       [-0.29861289,  0.95307362, -0.64044019]])

In [6]:
data * 10

array([[-11.66041108,   2.53656577,  11.09271926],
       [ -2.98612887,   9.53073619,  -6.4044019 ]])

In [7]:
data + data

array([[-2.33208222,  0.50731315,  2.21854385],
       [-0.59722577,  1.90614724, -1.28088038]])

In [8]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

### 1.2.1 创建ndarray 

In [11]:
data1 = [1,3,4,7,9]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([1, 3, 4, 7, 9])

In [14]:
data2 = [[1,5,8.8,3.2],[4.5,3.3,5.1,3]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1. , 5. , 8.8, 3.2],
       [4.5, 3.3, 5.1, 3. ]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.empty(4)

array([0., 0., 0., 0.])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.full(1)

TypeError: full() missing 1 required positional argument: 'fill_value'

In [27]:
np.full((2,3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.2.2 ndarray中数据类型 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;定义获取数据类型

In [7]:
arr1 = np.array([1,3,5,7,9], dtype = np.float64)
arr2 = np.array([0,2,4,6,8], dtype = np.int32)
arr1.dtype

dtype('float32')

In [4]:
arr2.dtype

dtype('int32')

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数据类型转换

In [13]:
# 整型转浮点型
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [12]:
float_arr = arr.astype(np.float16)
float_arr.dtype

dtype('float16')

In [14]:
# 浮点型转整型，小数部分会被截取删除
arr = np.array([1.1,2.2,4.4,6.6,7.7])
arr.dtype

dtype('float64')

In [37]:
arr = np.array(['1.2','3.54','3','4.43','2'], dtype=np.string_)
arr

array([b'1.2', b'3.54', b'3', b'4.43', b'2'], dtype='|S4')

In [34]:
# 数值字符串转数值类型
arr = np.array(['1','3','4','5','2'], dtype=np.string_)
arr

array([b'1', b'3', b'4', b'5', b'2'], dtype='|S1')

In [38]:
arr1 = arr.astype(np.float64)
arr1

array([1.2 , 3.54, 3.  , 4.43, 2.  ])

In [36]:
arr2 = arr.astype(np.int32)
arr2

array([1, 3, 4, 5, 2], dtype=int32)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;通过dtype为astype提供数据类型

In [40]:
int_array = np.arange(10)
float_array = np.array([1.3,3.3,4.2,5.1],dtype=np.float64)
int_array.astype(float_array.dtype)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])